name: todo_app_romavic
description: "TodoApp"
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.3.3
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  get_it: ^7.6.7
  go_router: ^13.2.0
  easy_localization: ^3.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  alarm: ^3.0.12
  flutter_datetime_picker_plus: ^2.1.0
  table_calendar:
  flutter_svg: ^2.0.9
  weekday_selector: ^1.1.0
  notification_permissions: ^0.6.1
  step_progress_indicator: ^1.0.2
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  mobx_codegen: ^2.1.1

flutter:

  uses-material-design: true

  assets:

    - assets/illustrations/
    - assets/music/