// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHiTmwGgAnz6pmaAsdjpYATmTncV5d2Jo',
    appId: '1:551312602581:android:bd700c536e453a6cae795c',
    messagingSenderId: '551312602581',
    projectId: 'todo-app-romavic',
    storageBucket: 'todo-app-romavic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIhSfu6O3wB2gVQePqOjZV_b0vcX33pks',
    appId: '1:551312602581:ios:fe3144020820553dae795c',
    messagingSenderId: '551312602581',
    projectId: 'todo-app-romavic',
    storageBucket: 'todo-app-romavic.appspot.com',
    androidClientId: '551312602581-ucs1rur26nhj21h34if2c5fl5pvbgi3j.apps.googleusercontent.com',
    iosClientId: '551312602581-og2sicdamghvl7q34sc7mhut0hdggg56.apps.googleusercontent.com',
    iosBundleId: 'todoapp.romavic.com.todoAppRomavic',
  );
}
